- name: copy pkg list
  copy: src=full_pkg.rpmlist dest=/tmp/

# TODO: only once
- name: install base pkgs
  shell: "xargs yum -y install < /tmp/full_pkg.rpmlist 2>&1 | tee /tmp/full_pkg_install.log.`date +%Y%m%d%H%M`"
